/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2018-10-26 at 13:28:43 UTC
 * Modify at your own risk.
 */

package org.ctoolkit.restapi.client.pubsub;

/**
 * Test model definition for InvoicingConfigBillingAddress.
 */
@SuppressWarnings( "javadoc" )
public final class InvoicingConfigBillingAddress
        extends com.google.api.client.json.GenericJson
{
    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private String businessName;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private String city;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private String country;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private Double latitude;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private Double longitude;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private String postcode;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private String street;

    /**
     * @return value or {@code null} for none
     */
    public String getBusinessName()
    {
        return businessName;
    }

    /**
     * @param businessName businessName or {@code null} for none
     */
    public InvoicingConfigBillingAddress setBusinessName( String businessName )
    {
        this.businessName = businessName;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getCity()
    {
        return city;
    }

    /**
     * @param city city or {@code null} for none
     */
    public InvoicingConfigBillingAddress setCity( String city )
    {
        this.city = city;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getCountry()
    {
        return country;
    }

    /**
     * @param country country or {@code null} for none
     */
    public InvoicingConfigBillingAddress setCountry( String country )
    {
        this.country = country;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Double getLatitude()
    {
        return latitude;
    }

    /**
     * @param latitude latitude or {@code null} for none
     */
    public InvoicingConfigBillingAddress setLatitude( Double latitude )
    {
        this.latitude = latitude;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Double getLongitude()
    {
        return longitude;
    }

    /**
     * @param longitude longitude or {@code null} for none
     */
    public InvoicingConfigBillingAddress setLongitude( Double longitude )
    {
        this.longitude = longitude;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getPostcode()
    {
        return postcode;
    }

    /**
     * @param postcode postcode or {@code null} for none
     */
    public InvoicingConfigBillingAddress setPostcode( String postcode )
    {
        this.postcode = postcode;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getStreet()
    {
        return street;
    }

    /**
     * @param street street or {@code null} for none
     */
    public InvoicingConfigBillingAddress setStreet( String street )
    {
        this.street = street;
        return this;
    }

    @Override
    public InvoicingConfigBillingAddress set( String fieldName, Object value )
    {
        return ( InvoicingConfigBillingAddress ) super.set( fieldName, value );
    }

    @Override
    public InvoicingConfigBillingAddress clone()
    {
        return ( InvoicingConfigBillingAddress ) super.clone();
    }

}
