/*
 * This code was generated by https://github.com/google/apis-client-generator/
 * (build: 2018-10-08 17:45:39 UTC)
 * on 2018-10-26 at 13:28:43 UTC
 * Modify at your own risk.
 */

package org.ctoolkit.restapi.client.pubsub;

/**
 * Test model definition for InvoicingConfig.
 */
@SuppressWarnings( "javadoc" )
public final class InvoicingConfig
        extends com.google.api.client.json.GenericJson
{
    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    @com.google.api.client.json.JsonString
    private java.lang.Long id;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private InvoicingConfigBillingAddress billingAddress;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private String currency;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private Boolean hasBillingAddress;

    /**
     * The value may be {@code null}.
     */
    @com.google.api.client.util.Key
    private Integer numberOfDays;

    /**
     * @return value or {@code null} for none
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * @param id id or {@code null} for none
     */
    public InvoicingConfig setId( java.lang.Long id )
    {
        this.id = id;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public InvoicingConfigBillingAddress getBillingAddress()
    {
        return billingAddress;
    }

    /**
     * @param billingAddress billingAddress or {@code null} for none
     */
    public InvoicingConfig setBillingAddress( InvoicingConfigBillingAddress billingAddress )
    {
        this.billingAddress = billingAddress;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public String getCurrency()
    {
        return currency;
    }

    /**
     * @param currency currency or {@code null} for none
     */
    public InvoicingConfig setCurrency( String currency )
    {
        this.currency = currency;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Boolean getHasBillingAddress()
    {
        return hasBillingAddress;
    }

    /**
     * @param hasBillingAddress hasBillingAddress or {@code null} for none
     */
    public InvoicingConfig setHasBillingAddress( Boolean hasBillingAddress )
    {
        this.hasBillingAddress = hasBillingAddress;
        return this;
    }

    /**
     * @return value or {@code null} for none
     */
    public Integer getNumberOfDays()
    {
        return numberOfDays;
    }

    /**
     * @param numberOfDays numberOfDays or {@code null} for none
     */
    public InvoicingConfig setNumberOfDays( Integer numberOfDays )
    {
        this.numberOfDays = numberOfDays;
        return this;
    }

    @Override
    public InvoicingConfig set( String fieldName, Object value )
    {
        return ( InvoicingConfig ) super.set( fieldName, value );
    }

    @Override
    public InvoicingConfig clone()
    {
        return ( InvoicingConfig ) super.clone();
    }

}
